server:
      port: 8001

api:
    url: "http://localhost"
logging:
  config: classpath:log4j2.xml

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/book
  application:
      name: mongoweb